# Remove newline before the first prompt,
# but echo out a newline as a precmd hook in zshrc:
# ```zsh
# precmd() {
#   precmd() {
#     echo
#   }
# }```

add_newline = false

format = """
[╭─────⟨](bold blue)$username\
$hostname\
$directory\
$git_branch\
$git_commit\
$git_state\
$git_metrics\
$git_status\
$c\
$cmake\
$cobol\
$daml\
$dart\
$deno\
$dotnet\
$elixir\
$elm\
$erlang\
$fennel\
$golang\
$guix_shell\
$haskell\
$haxe\
$helm\
$java\
$julia\
$kotlin\
$gradle\
$lua\
$nim\
$nodejs\
$ocaml\
$opa\
$perl\
$php\
$pulumi\
$purescript\
$python\
$raku\
$rlang\
$red\
$ruby\
$rust\
$scala\
$solidity\
$swift\
$terraform\
$vlang\
$vagrant\
$zig\
$buf\
$nix_shell\
$conda\
$sudo\
$line_break\
$character"""

right_format = """$cmd_duration $time"""

[character]
success_symbol = '[╰](bold green)[─](bold green)[Σ](bold green)'
error_symbol = '[╰](bold red)[─](bold red)[Σ](bold red)'

[directory]
format = " [$path]($style) "
truncation_length = 3
truncation_symbol = ""

[cmd_duration]
min_time = 1_000
format = "took [$duration]($style) |"
style = "dimmed"
show_milliseconds = true

[time]
format = "[$time]($style)"
disabled = false
style = "dimmed"
time_format = "%F %T"

# Disable the package module, hiding it from the prompt completely
[package]
disabled = true
