#!/bin/sh

# Tell cron where to send notifications
export DISPLAY=:0
export DBUS_SESSION_BUS_ADDRESS="unix:path=/run/user/1000/bus"

# Get some important values
WARNING_LEVEL=40
BATTERY_DISCHARGING=`acpi -b | grep -c "Discharging"`
BATTERY_LEVEL=`acpi -b | grep -P -o '[0-9]+(?=%)'`

# Temporary files that indicate whether full or empty
# notifcation has been sent
EMPTY_FILE=/tmp/batteryempty
FULL_FILE=/tmp/batteryfull

# Reset notifications if the computer is charging/discharging
if [ $BATTERY_DISCHARGING -eq 1 ] && [ -f $FULL_FILE ]; then
    rm $FULL_FILE
elif [ $BATTERY_DISCHARGING -eq 0 ] && [ -f $EMPTY_FILE ]; then
    rm $EMPTY_FILE
fi

# Send notifications if haven't been sent yet
if [ $BATTERY_LEVEL -gt 95 ] && [ $BATTERY_DISCHARGING -eq 0 ] && [ ! -f $FULL_FILE ]; then
    notify-send "Battery Charged" "Battery is fully charged." -i "battery" -r 9991
    touch $FULL_FILE

elif [ $BATTERY_LEVEL -le $WARNING_LEVEL ] && [ $BATTERY_DISCHARGING -eq 1 ] && [ ! -f $EMPTY_FILE ]; then
    notify-send "Charge yo computer bruh" "${BATTERY_LEVEL}% left." -u critical -i "battery-critical" -r 9991
    touch $EMPTY_FILE
fi
